language: c # change this to objective-c to test on a mac machine
sudo: required
env:
  global:
    - HAXE_VER=3.2.1
  matrix:
    - TARGET=swf

matrix:
  fast_finish: true
  allow_failures:
    - env: SOME_ENV_HERE=some_opt

before_install:
  - travis_retry git clone --depth=50 --branch=master git://github.com/waneck/travis-hx.git ~/travis-hx

install:
  - ~/travis-hx/setup.sh
  - travis_retry haxelib install hunit
  - travis_retry git clone https://github.com/StablexUI/Core
  - travis_retry haxelib dev stablexui-core Core
  - travis_retry git clone https://github.com/StablexUI/Tests
  - travis_retry haxelib dev stablexui-tests Tests
  - travis_retry haxelib list stablexui-tests

script:
  - cd $TRAVIS_BUILD_DIR
  - HXFLAGS="-cp src -lib stablexui-tests -swf-version 11.3 -main StablexUITests -D HUNIT_TEST_DIR=tests" ~/travis-hx/build.sh
  - ~/travis-hx/runtests.sh $FILENAME # this will set the $FILENAME defined on the environment variable to run the tests